# Generated by Django 3.1.7 on 2021-07-19 09:26

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postpoint',
            old_name='post_header',
            new_name='post_point_header',
        ),
        migrations.RemoveField(
            model_name='postpoint',
            name='post_images',
        ),
        migrations.AddField(
            model_name='postpoint',
            name='post_point_images',
            field=models.ImageField(blank=True, upload_to=blog.models.save_images, verbose_name='Изображение пункта'),
        ),
    ]
