# Generated by Django 3.1.7 on 2021-07-19 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210719_1226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postpoint',
            old_name='post_point_images',
            new_name='post_point_image',
        ),
    ]
